<?php

namespace HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClothRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClothRepository extends EntityRepository
{
}
