<?php

namespace HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LongVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LongVideoRepository extends EntityRepository
{
}
