<?php

namespace HomeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoPrendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPrendaRepository extends EntityRepository
{
}
